version: 0.2
phases:
  pre_build:
    commands:
      - echo Dep install started on `date`
      - npm install -g typescript
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
  commands:
    - echo Build completed on `date`
artifacts:
  files:
    - dist/**/*
    - node_modules/**/*
    - package.json
    - package-lock.json
