version: 0.2
install:
  runtime-versions:
    nodejs: 12
phases:
  pre_build:
    commands:
      - echo Dep install started on `date`
      - npm install -g typescript
      - PLAYWRIGHT_BROWSERS_PATH=0 npm install
      - npm audit fix
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - PLAYWRIGHT_BROWSERS_PATH=0 npm install --only=prod
      - npm audit fix
      - echo Build completed on `date`
artifacts:
  files:
    - .platform/**/*
    - dist/**/*
    - node_modules/**/*
    - package.json
    - package-lock.json
