version: 0.2
phases:
install:
runtime-versions:
nodejs: 12
commands:
  - npm install -g typescript
  - npm install
pre_build:
  - echo No PreBuild
build:
commands:
  - echo Build started on `date`
  - npm run build
post_build:
commands:
  - echo Build completed on `date`
cache:
paths:
  - 'node_modules/**/*'
artifacts:
files:
  - '**/*'
name: playwright-server-$(date +%Y-%m-%d)
