version: 0.2
install:
  runtime-versions:
    nodejs: 12
phases:
  pre_build:
    commands:
      - echo Dep install started on `date`
      - PLAYWRIGHT_BROWSERS_PATH=0 npm install -g typescript
      - PLAYWRIGHT_BROWSERS_PATH=0 npm install
      - npm audit fix
  build:
    commands:
      - echo Build started on `date`
      - PLAYWRIGHT_BROWSERS_PATH=0 npm run build
artifacts:
  files:
    - .platform/**/*
    - dist/**/*
    - node_modules/**/*
    - package.json
    - package-lock.json
